version: "3.8"
services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"